// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Br0bertinus/callsheet-api/server (interfaces: GameServicer)
//
// Generated by this command:
//
//	mockgen -destination=server/mocks/mock_game_service.go -package=mocks github.com/Br0bertinus/callsheet-api/server GameServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/Br0bertinus/callsheet-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGameServicer is a mock of GameServicer interface.
type MockGameServicer struct {
	ctrl     *gomock.Controller
	recorder *MockGameServicerMockRecorder
	isgomock struct{}
}

// MockGameServicerMockRecorder is the mock recorder for MockGameServicer.
type MockGameServicerMockRecorder struct {
	mock *MockGameServicer
}

// NewMockGameServicer creates a new mock instance.
func NewMockGameServicer(ctrl *gomock.Controller) *MockGameServicer {
	mock := &MockGameServicer{ctrl: ctrl}
	mock.recorder = &MockGameServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameServicer) EXPECT() *MockGameServicerMockRecorder {
	return m.recorder
}

// DailyChallenge mocks base method.
func (m *MockGameServicer) DailyChallenge() (domain.NewGameResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DailyChallenge")
	ret0, _ := ret[0].(domain.NewGameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DailyChallenge indicates an expected call of DailyChallenge.
func (mr *MockGameServicerMockRecorder) DailyChallenge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DailyChallenge", reflect.TypeOf((*MockGameServicer)(nil).DailyChallenge))
}

// GetActor mocks base method.
func (m *MockGameServicer) GetActor(id int) (domain.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActor", id)
	ret0, _ := ret[0].(domain.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActor indicates an expected call of GetActor.
func (mr *MockGameServicerMockRecorder) GetActor(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActor", reflect.TypeOf((*MockGameServicer)(nil).GetActor), id)
}

// NewGame mocks base method.
func (m *MockGameServicer) NewGame(startActorID, targetActorID int) (domain.NewGameResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGame", startActorID, targetActorID)
	ret0, _ := ret[0].(domain.NewGameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewGame indicates an expected call of NewGame.
func (mr *MockGameServicerMockRecorder) NewGame(startActorID, targetActorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGame", reflect.TypeOf((*MockGameServicer)(nil).NewGame), startActorID, targetActorID)
}

// SearchMovies mocks base method.
func (m *MockGameServicer) SearchMovies(query string) ([]domain.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMovies", query)
	ret0, _ := ret[0].([]domain.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMovies indicates an expected call of SearchMovies.
func (mr *MockGameServicerMockRecorder) SearchMovies(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMovies", reflect.TypeOf((*MockGameServicer)(nil).SearchMovies), query)
}

// SearchPeople mocks base method.
func (m *MockGameServicer) SearchPeople(query string) ([]domain.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPeople", query)
	ret0, _ := ret[0].([]domain.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPeople indicates an expected call of SearchPeople.
func (mr *MockGameServicerMockRecorder) SearchPeople(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPeople", reflect.TypeOf((*MockGameServicer)(nil).SearchPeople), query)
}

// ValidateStep mocks base method.
func (m *MockGameServicer) ValidateStep(req domain.ValidateStepRequest) (domain.ValidateStepResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateStep", req)
	ret0, _ := ret[0].(domain.ValidateStepResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateStep indicates an expected call of ValidateStep.
func (mr *MockGameServicerMockRecorder) ValidateStep(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateStep", reflect.TypeOf((*MockGameServicer)(nil).ValidateStep), req)
}
